### ISSUE TITLE
BLOB Storage Writer API Proxy app

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/mvp-icap-service#1]
Develop an app that conforms to the interface required by the gw_rebuild ICAP Resource.

Input file should be written to the BLOB storage, using a supplied connection string configuration item.
Rebuild file should be read from the location specified in the Transaction Outcome received on the Service Bus (connection string supplied as configuration item).

**Comment by dtollaku** [comment]
@BigPeeg is this done? Should we need to move to QA/Review?

**Comment by BigPeeg** [comment]
@dtollaku I need to get the Unit tests passing first.

**Comment by NadHodeGW** [comment]
This issue has been tested using the test client to test that documents are successfully processed as part of the Test issue #22
