### ISSUE TITLE
Processed file is corrupted after rebuild 

### ISSUE THREAD

**Issue by NadHodeGW** [filetrust/mvp-icap-service#20]

**Comment by dpatel7** [comment]
trying to download file from https://www.gov.uk.glasswall-icap.com/register-milk-production-holding/food-standards-agency. once is downloaded try and open the file. the file is corrupted. try and run through file-drop.co.uk identified as unsupported file. 
![image](https://user-images.githubusercontent.com/61416876/92718441-be62b400-f359-11ea-9544-05069f6384d0.png)
