### ISSUE TITLE
Dockerise BLOB Storage Writer API Proxy app

### ISSUE THREAD

**Issue by BigPeeg** [filetrust/mvp-icap-service#5]
In addition to supporting the ICAP Server, the API Proxy App needs to be installed into the specified location of the Docker container.

**Comment by BigPeeg** [comment]
This issue is a first step to deployment of the mvp-icap-server. Pipeline modifications are required before the container and its contents can be tested.

**Comment by NadHodeGW** [comment]
Validated as part of issue #1
